services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Replace with your Dockerfile's path if it's different
    container_name: app
    environment:
      - TEST_PARAMETER_SECRET=helloworldlocaldocker
    ports:
      - "8081:8080"  # Adjust the port if necessary